### PR TITLE
add support for enumerated field types

### PR DESCRIPTION
**Pull request by venediktov**
I have included your lib for my project at work, had to do few workarounds but most of the library worked for me.

 It would be nice  if your library could handle enumerated field types as well. The changes and tests are included in my PR , I put the check for enumerated after checking for list type in `query.py` for the reason I don't know yet how to test for List[Enum] and I am not sure support for this type of field  is ever needed. Feel free to change suggest in my PR.

### CODE REVIEW

**Comment by BeatsuDev** [comment]
I'll take a look at this as soon as I have time! Thanks for the PR request 😄

**Comment by BeatsuDev** [comment]
Looks great! Thanks for adding the test as well.

**Comment by BeatsuDev** [comment]
Hey @venediktov, I've revisited this project and completely changed a lot of syntax. It should now support all the basic types of int, float, str and bool as well as enums and lists of any of the types (e.g. `List[Enum]`). If you're still using this package in some project, I would love to hear if the current implementation of enum still satisfies your usage 😃

**Comment by venediktov** [comment]
Hi @BeatsuDev , I am gonna check with my python team and get back to you, thank you!

**Comment by BeatsuDev** [comment]
@venediktov it recently came to my attention that composing dynamic GraphQL queries already exists as a part of the `gql` python package. https://gql.readthedocs.io/en/latest/advanced/dsl_module.html

I just want to give you a heads up that if you're looking for a more stable solution, I suggest using that module instead. If you find this package useful, then I would recommend pinning the exact version of this package to avoid potentially breaking changes.

I haven't quite used this package enough or received enough issues to see if the current syntax and conceptual modelling of the solution holds up well in all types of GraphQL projects, so I don't feel comfortable bumping it up to a minor or major version yet (at which point I would start thinking of backwards compatibility).

**Comment by venediktov** [comment]
@BeatsuDev sorry for not getting back to you earlier. So majority of our code uses gql , however it did not  not support DSL style coding or there was something else as I could not use  python data classes that would produce valid graphQL request format?
I could be wrong or misleading you, this is as far as I remember :-)

**Comment by ericbstie** [comment]
@venediktov I think you're right. A quick search didn't reveal any way of easily converting dataclasses to gql queries with `gql`'s DSL at least... I'm glad this repository actually has a use-case then! 😃

The latest update of `gqlrequests` only attempts to improve the readability of the syntax and doesn't add much more features or fix any bugs - it just changes a lot. If you and your team *do* decide to upgrade to the latest version, it might be good to know that if you want to convert dataclasses to query strings you will first have to use the `from_pydantic` method to create a QueryBuilder (example below). Also, making a dataclass inherit from `QueryBuilder` now fails (also shown below).

All this is to say that if the package is working fine for your team as it is now, then I would suggest pinning the version to the one you are currently using. If your team upgrades, then here's the new syntax:
```py
from dataclasses import dataclass
import gqlrequests

@dataclass
class Example:
    test: int

ExampleBuilder = gqlrequests.from_pydantic(Example)
print(ExampleBuilder().build())
```
This on the other hand **DOES NOT WORK**:
```py
# DOES NOT WORK
@dataclass
class Example(gqlrequests.QueryBuilder):
    test: int
```

**Comment by ericbstie** [comment]
It seems like this PR was added after v0.0.7, but then I started rewriting a whole bunch and released v0.0.8... Meaning that supporting enums isn't in any version release before the rewrites starting v0.0.8 afaik... That's my rookie mistake as this should have definitely been released before I started rewriting everything... 

If you need enum support, you might be required to update to the newer version of this package. If the new syntax requires too much work to implement in your code base, an alternative would be to fork the repo and reset back to this commit: bc123d95a05366e065f30eea3aba369916dbbbf3 and then build the package from source and it include it manually in the project. You could also just copy whatever code you need from this codebase and paste it in your code base. Sorry for the mistake...

**Pull request merged**
